#!/usr/bin/env perl

use v5.18;
use strict;
use warnings;

use JSON::PP;

sub slurp_file {
    my ($fn) = @_;

    local $/;
    open my $fh, '<', $fn or die $!;
    my $contents = <$fh>;
    close $fh;

    return $contents;
}

sub parse_json {
    my ($fn) = @_;

    my $contents = slurp_file($fn);
    my $json = JSON::PP->new->utf8;

    return $json->utf8(0)->decode($contents);
}

sub to_string {
    my ($json) = @_;

    my $title = $json->{Title};
    my $time = $json->{Timestamp};
    my $content = $json->{Content};
    $content =~ s/\\n/\n/g;

    return join("\n", ($title, $time, '', $content));
}

sub main {
    my (@filenames) = @_;
    for my $filename (@filenames) {
        my $json = parse_json($filename);
        say to_string($json);
    }

    return 0;
}

exit main(@ARGV);
